### ISSUE TITLE
bro you posted all your secrets in your code!

### ISSUE THREAD

**Issue by DTrejo** [lucasad/node-snapchat#2]

**Comment by kenany** [comment]
Looks like they're the same secrets used in [snaphax](https://github.com/tlack/snaphax/blob/f082ecf0a7bd3648eb919c4c934c6458b6f04bdf/snaphax.php#L27-35). Ref: tlack/snaphax#10.

**Comment by bored-engineer** [comment]
I don't see any issues with this other than from a legal standpoint. But for sure it would be important to read through the linked issue regarding the legality of the keys being stored in the code/documentation.

**Comment by DTrejo** [comment]
Nvm close this then! All power to you for not signing up for your own api
keys :):) that's always annoying.

## 

Please excuse any brevity

**Comment by lucasad** [comment]
There are no API keys except the official one AFIK. If this changes, I'll remove the keys.
