### ISSUE TITLE
Client#upload returns an error message from Google App Engine

### ISSUE THREAD

**Issue by jdan** [lucasad/node-snapchat#3]
Using the following:

``` javascript
var fs = require('fs');
var snapchat = new (require('snapchat').Client)();

snapchat.login(USERNAME, PASSWORD);
var stream = fs.createReadStream('sloth.jpg');
snapchat.upload(stream, FRIEND);
```

I receive the following error:

```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>If the problem persists, please <A HREF="http://code.google.com/appengine/community.html">report</A> your problem and mention this error message and the query that caused it.</h2>
<h2></h2>
</body></html>
```

Any ideas why? Have they changed the endpoint for uploads?

**Comment by kaushal** [comment]
I'm having this error as well. Any solutions?

**Comment by lucasad** [comment]
I think they've changed the server endpoint. I'll investigate and fix this

**Comment by octopi** [comment]
If you take a look at this diff (https://github.com/dstelljes/php-snapchat/commit/31fe8ec88e7c6b49b28fc742d6518d949076fa58) from the PHP library, it looks like the formatting of the media ID may have changed?

However, even adding in the `~` between username and UUID and upping the versions didn't seem to work. Any clue on where else to look?

**Comment by kaushal** [comment]
The php library seems to be working for uploads. So currenlty i'm writing
in node, and handing off to a php script to upload the pic. Not the best
solution, but I really don't want to write this app in php.

On Wed, Nov 27, 2013 at 4:34 PM, David Hu notifications@github.com wrote:

> If you take a look at this diff (dstelljes/php-snapchat@31fe8echttps://github.com/dstelljes/php-snapchat/commit/31fe8ec88e7c6b49b28fc742d6518d949076fa58)
> from the PHP library, it looks like the formatting of the media ID may have
> changed?
> 
> However, even adding in the ~ between username and UUID and upping the
> versions didn't seem to work. Any clue on where else to look?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nykac/node-snapchat/issues/3#issuecomment-29422004
> .

## 

Thanks,
Kaushal Parikh

**Comment by octopi** [comment]
Alright after fiddling around a little more, the server endpoint didn't change—the upload functionality of this library still works as-is.

What version of node were you guys using? I think this is an issue with the new streams introduced in node 0.10 and incompatibility with the multipart-form-stream dependency, which hasn't been updated in over a year. If you switch to 0.8.x, things are looking better in uploadland.

@nykac perhaps be a little stricter about engine version in package.json?

FWIW, I tried substituting [node-form-data](https://github.com/felixge/node-form-data) for multipart-form-stream but couldn't get it to quite work. If I figure it out I'll submit a pull request.

**Comment by lucasad** [comment]
@octopi Feel free to change the form data dependency as long as it doesn't have too many sub sub-dependencies I'm fine with it.
I'll check out node-form-data as well. I've also had issues with getting crypto to work properly in node (hence the handoff to the openssl binary).

**Comment by lucasad** [comment]
@octopi what version of node were you using?

**Comment by lucasad** [comment]
I think I have a fix. I'll commit the changes soon. It looks like it would discard part of the encrypted stream before it got to be uploaded. I just needed to pause the stream immediately.

**Comment by lucasad** [comment]
Ok, I've got it working. I'll commit and push the changes this weekend.

**Comment by lucasad** [comment]
Crap, its a heisenbug, it works when I test it, but when I actually require() it after installing it from npm, uploads don't work.

``` javascript
var sc = require('./snapchat');
var c = new sc.Client();
var fs = require('fs');

c.login('USERNAME', 'password')
.then(function() {
    var blob = fs.createReadStream('snap.jpg');
    return c.upload(blob);
}, function(err) {
    console.log('Upload Error');
    console.log(err);
})
.then(function(id) {
    return c.send(id, 'FRIENDS NAME');
}).then(function(resp){
    console.log('It worked');
}, function(err) {
    console.log('Failed to send the snap');
    console.log(err);
});
```

**Comment by jdan** [comment]
You've pushed to npm and updated? I'm notorious for testing on old versions of my node modules and freaking out thinking the version on npm is still broken.

**Comment by lucasad** [comment]
@jdan i rm -r'd the node_modules to be safe

**Comment by lucasad** [comment]
@jdan Can you test this? Also, should I create a 3rd event emitter based wrapper, or did the event emitter not make much sense for real world usage.

**Comment by jdan** [comment]
I'm getting the same error as I originally filed. Using `require('./node-snapchat')` pointing to a clone of this repo.

**Comment by lucasad** [comment]
I tested this on another box, and it doesn't work.
It only seems to work in a certain directory.
REALLY WIERD

**Comment by lucasad** [comment]
Ok, it seems to only work with 0.8.x. I'll do some more investigation as to how to get it working with 0.10.x.

**Comment by lucasad** [comment]
Ok, I figured it out. The multipart encoder uses a function called `_read`, which node 0.10.x streams call until it returns `null`. Seems it was called by node at the wrong time.

**Comment by jdan** [comment]
Awesome work :)

![sc](https://i.cloudup.com/C9HjheQucl-600x600.jpeg)
